<?xml version="1.0"?>

<robot name="kopterworx" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Math constants -->
  <xacro:property name="sin45" value="0.7071068" />
  <xacro:property name="cos45" value="0.7071068" />

  <!-- Body Properties -->
  <xacro:property name="namespace" value="kopterworx" />
  <xacro:property name="mesh_file" value="px4_gazebo/models/kopterworx/meshes/kopterworx_model_simple.dae" />
  <xacro:property name="mesh_scale" value="0.1" />
  <xacro:property name="prop_scale" value="0.002" />
  <xacro:property name="mass" value="9" />  <!-- [kg] -->
  <xacro:property name="body_width" value="0.3" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.6" /> <!-- [m] -->
  <xacro:property name="arm_length" value="0.52" /> <!-- [m] -->
  <xacro:property name="rotor_x_offset" value="${arm_length*cos45}" /> <!-- [m] -->
  <xacro:property name="rotor_y_offset" value="${arm_length*sin45}" /> <!-- [m] -->
  <xacro:property name="rotor_offset_top" value="0.115" /> <!-- [m] -->

  <!-- Rotor constants -->
  <xacro:property name="mass_rotor" value="0.01" /> <!-- [kg] -->
  <xacro:property name="radius_rotor" value="0.285" /> <!-- [m] -->
  <xacro:property name="motor_constant" value="0.000285576174524687" /> <!-- [kg*m/s^2] -->
  <xacro:property name="moment_constant" value="0.041365783102071" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0125" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.0125" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="600" /> <!-- [rad/s] 600 -->
  <xacro:property name="rotor_drag_coefficient" value="8.06428e-05" />
  <xacro:property name="rolling_moment_coefficient" value="0.000001" />
  <xacro:property name="rotor_velocity_slowdown_sim" value="15" />

  <!-- Property Blocks -->
  <xacro:property name="body_inertia">  
    <inertia ixx="0.303755" ixy="0.0004484919" ixz="0.0010159727" iyy="0.27722" iyz="-0.001806885" izz="0.469164" />
  </xacro:property>

  <!-- inertia of a single rotor, assuming it is a cuboid. Height=3mm, width=15mm -->
  <xacro:property name="rotor_inertia">
    <xacro:box_inertia x="${radius_rotor}" y="0.015" z="0.003" mass="${mass_rotor*rotor_velocity_slowdown_sim}" />
  </xacro:property>
  
  <!-- Included URDF Files -->
  <xacro:include filename="$(find px4_gazebo)/models/util/multirotor_base.urdf.xacro" />

  <!-- Instantiate multirotor_base_macro once -->
  <xacro:multirotor_base_macro
    robot_namespace="$(arg namespace)"
    mass="${mass}"
    body_width="${body_width}"
    body_height="${body_height}"
    mesh_file="${mesh_file}"
    mesh_scale="${mesh_scale}">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_macro>

  <!-- Instantiate rotors -->
  <xacro:custom_vertical_rotor
    robot_namespace="$(arg namespace)"
    suffix="front_left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red"
    prop_scale="${prop_scale}">
    <origin xyz="${rotor_x_offset} ${rotor_y_offset} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:custom_vertical_rotor>

  <xacro:custom_vertical_rotor
    robot_namespace="$(arg namespace)"
    suffix="front_right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="0"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue"
    prop_scale="${prop_scale}">
    <origin xyz="${rotor_x_offset} -${rotor_y_offset} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:custom_vertical_rotor>

  <xacro:custom_vertical_rotor
    robot_namespace="$(arg namespace)"
    suffix="back_left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue"
    prop_scale="${prop_scale}">
    <origin xyz="-${rotor_x_offset} ${rotor_y_offset} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:custom_vertical_rotor>

  <xacro:custom_vertical_rotor
    robot_namespace="$(arg namespace)"
    suffix="back_right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red"
    prop_scale="${prop_scale}">
    <origin xyz="-${rotor_x_offset} -${rotor_y_offset} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:custom_vertical_rotor>

  <gazebo reference="base_link">
    <dampingFactor>0.001</dampingFactor>
  </gazebo>

</robot>